LIBGEN_UPLOADER_VERSION = "0.1.0"

FICTION_UPLOAD_URL = "https://library.bz/fiction/upload/"
SCITECH_UPLOAD_URL = "https://library.bz/main/upload/"

UPLOAD_USERNAME = "genesis"
UPLOAD_PASSWORD = "upload"

METADATA_FORM_ALLOWED_LANGUAGES = [
    "Abkhaz",
    "Afar",
    "Afrikaans",
    "Akan",
    "Albanian",
    "Amharic",
    "Arabic",
    "Aragonese",
    "Armenian",
    "Assamese",
    "Avaric",
    "Avestan",
    "Aymara",
    "Azerbaijani",
    "Bambara",
    "Bashkir",
    "Basque",
    "Belarusian",
    "Bengali",
    "Bihari",
    "Bislama",
    "Bosnian",
    "Breton",
    "Bulgarian ",
    "Burmese",
    "Catalan",
    "Chamorro",
    "Chechen",
    "Chichewa",
    "Chinese",
    "Chuvash",
    "Cornish",
    "Corsican",
    "Cree",
    "Croatian",
    "Czech",
    "Danish",
    "Divehi",
    "Dutch",
    "Dzongkha",
    "English",
    "Esperanto",
    "Estonian",
    "Ewe",
    "Faroese",
    "Fijian",
    "Finnish",
    "French",
    "Fula",
    "Galician",
    "Ganda",
    "Georgian",
    "German",
    "Greek",
    "Guaraní",
    "Gujarati",
    "Haitian",
    "Hausa",
    "Hebrew",
    "Herero",
    "Hindi",
    "Hiri Motu",
    "Hungarian",
    "Icelandic",
    "Ido",
    "Igbo",
    "Indonesian",
    "Interlingua",
    "Interlingue",
    "Inuktitut",
    "Inupiaq",
    "Irish",
    "Italian",
    "Japanese",
    "Javanese",
    "Kalaallisut",
    "Kannada",
    "Kanuri",
    "Kashmiri",
    "Kazakh",
    "Khmer",
    "Kikuyu",
    "Kinyarwanda",
    "Kirundi",
    "Komi",
    "Kongo",
    "Korean",
    "Kurdish",
    "Kwanyama",
    "Kyrgyz",
    "Lao",
    "Latin",
    "Latvian",
    "Limburgish",
    "Lingala",
    "Lithuanian",
    "Luba",
    "Luxembourgish",
    "Macedonian",
    "Malagasy",
    "Malay",
    "Malayalam",
    "Maltese",
    "Manx",
    "Marathi",
    "Marshallese",
    "Mongolian",
    "Māori",
    "Nauru",
    "Navajo",
    "Ndonga",
    "Nepali",
    "North Ndebele",
    "Northern Sami",
    "Norwegian",
    "Norwegian Bokmål",
    "Norwegian Nynorsk",
    "Nuosu",
    "Occitan",
    "Ojibwe",
    "Old Church Slavonic",
    "Oriya",
    "Oromo",
    "Ossetian",
    "Panjabi",
    "Pashto",
    "Persian",
    "Polish",
    "Portuguese",
    "Pāli",
    "Quechua",
    "Romanian",
    "Romansh",
    "Russian",
    "Russian (Old)",
    "Samoan",
    "Sango",
    "Sanskrit",
    "Sardinian",
    "Scottish Gaelic",
    "Serbian",
    "Shona",
    "Sindhi",
    "Sinhala",
    "Slovak",
    "Slovene",
    "Somali",
    "South Ndebele",
    "Southern Sotho",
    "Spanish",
    "Sundanese",
    "Swahili",
    "Swati",
    "Swedish",
    "Tagalog",
    "Tahitian",
    "Tajik",
    "Tamil",
    "Tatar",
    "Telugu",
    "Thai",
    "Tibetan Standard",
    "Tigrinya",
    "Tonga",
    "Tsonga",
    "Tswana",
    "Turkish",
    "Turkmen",
    "Twi",
    "Uighur",
    "Ukrainian",
    "Urdu",
    "Uzbek",
    "Venda",
    "Vietnamese",
    "Volapük",
    "Walloon",
    "Welsh",
    "Western Frisian",
    "Wolof",
    "Xhosa",
    "Yiddish",
    "Yoruba",
    "Zhuang",
    "Zulu",
]

METADATA_FORM_SCHEMA = {
    # title and language are not required at this stage as they can also come from the book file or external metadata source
    "title": {"type": "string"},
    "language": {
        "type": "string",
        "allowed": [x.lower() for x in METADATA_FORM_ALLOWED_LANGUAGES],
    },
    "authors": {"type": "list", "schema": {"type": "string"}},
    "edition": {"type": "string"},
    "series": {"type": "string"},
    "pages": {"type": "integer", "min": 1},
    "year": {"type": "integer"},
    "publisher": {"type": "string"},
    "ISBNs": {"type": "list", "schema": {"type": "string"}},
    "description": {"type": "string"},
    "comment": {"type": "string"},
}